name: Build Image

on: push

env:
  - CADDY_VERSION: "2.7.6"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Docker
        uses: docker/setup-buildx-action@edfb0fe6204400c56fbfd3feba3fe9ad1adfa345
      - name: Authenticate to GHCR
        uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@9f6f8c940b91232557f8699b21341a08624a8dce
        with:
          push: true
          tags: lorwp/caddy-cloudflaredns:${[ env.CADDY_VERSION ]}



    